### ISSUE TITLE
Kafka 0.10.2.0

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-kafka#127]
This is created to track our upgrade to support Kafka 0.10.2.0 client.

**Comment by ppf2** [comment]
Related: https://github.com/logstash-plugins/logstash-input-kafka/issues/178

**Comment by original-brownbear** [comment]
@suyograo input and output merged => publish both ? :)

**Comment by suyograo** [comment]
@original-brownbear yes!

**Comment by suyograo** [comment]
Fixed in #133
