### ISSUE TITLE
Unable to bootstrap the master branch

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-output-kafka#13]
When trying to run ```bundle install`` I get this error, so the user can not continue building and setting up the project.
```
LoadError: no such file to load -- maven/ruby/maven
An error occurred while installing jruby-kafka (1.1.1), and Bundler cannot
continue.
Make sure that `gem install jruby-kafka -v '1.1.1'` succeeds before bundling.
➜  logstash-output-kafka git:(master) gem install bundler; bundle install
```

**Comment by joekiller** [comment]
This should be fixed with `jruby-kafka 1.1.2` (available now)

**Comment by purbon** [comment]
Cool, thanks. Checking ;-)

**Comment by purbon** [comment]
I've check this and works perfect for me. Do you think @joekiller we can close this issue now?

**Comment by joekiller** [comment]
Yup close away
