### ISSUE TITLE
Poor Performance Vs. Old version of plugin found in logstash 1.4.2

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-kafka#14]
running theory is that `event.sprintf` is REALLY SLOW and should not be happening on each event when formatting `topic_id`

line: https://github.com/logstash-plugins/logstash-output-kafka/blob/master/lib/logstash/outputs/kafka.rb#L148

**Comment by joekiller** [comment]
I'll try to get around to benchmarking some stacks. But it might be a week
or so.

**Comment by talevy** [comment]
false alarm. closing.

**Comment by colinsurprenant** [comment]
please check elastic/logstash#2899
