### ISSUE TITLE
Kafka 0.8.2+ producer

### ISSUE THREAD

**Issue by joekiller** [logstash-plugins/logstash-output-kafka#15]
I recently implemented the 0.8.2 producer in jruby-kafka (https://github.com/joekiller/jruby-kafka/issues/24) and it could be useful for this project.

**Comment by mheese** [comment]
+1

**Comment by talevy** [comment]
WIP branch with updated producer. Still figuring out how to best integrate this in a backwards compatible way.
https://github.com/talevy/logstash-output-kafka/tree/new-producer

**Comment by joekiller** [comment]
Being that 1.5 is not released yet it could be argued to just make this the
default. The producer is noted to be 0.8.X compatible here:
http://blog.confluent.io/2014/12/02/whats-coming-in-apache-kafka-0-8-2/

**Comment by Mogztter** [comment]
> Being that 1.5 is not released yet it could be argued to just make this the default.

I agree :+1:

**Comment by keithchambers** [comment]
:+1:

**Comment by allenmchan** [comment]
Logstash is already on 1.5.x. Is it currently using the 0.8.2 producer? This issue hasnt been touched in 3 months

**Comment by allenmchan** [comment]
Nevermind, looks like the new producer was merged in 
https://github.com/logstash-plugins/logstash-output-kafka/pull/21

This issue should be closed to avoid confusion?

**Comment by talevy** [comment]
@allenmchan it is in master, but it has not been officially released in rubygems yet for compatibility reasons. That is why this has not yet been closed.

**Comment by allenmchan** [comment]
ok now i am confused why you cannot push the update to rubygems. Joekiller's comment said it is backward compatible. Asking everyone who uses this to build our own gem does not make sense

**Comment by talevy** [comment]
@allenmchan, Joekiller's library is backwards compatible. but the logstash plugin is not. mainly for the reason of simplicity.

**Comment by talevy** [comment]
@allenmchan we are finalizing how we handle pre-release plugins like beta releases within Logstash, and then we will go ahead and release this. We do not wish for people to run `bin/plugin update logstash-output-kafka` and have everything break on them without them being aware of the changes.

**Comment by suyograo** [comment]
@allenmchan this definitely is not backwards compatible with LS 1.x. Most of the config options have changed.

**Comment by allenmchan** [comment]
@suyograo is there a github issue or pull request that i can track to follow when this is actually available on rubygems?

**Comment by suyograo** [comment]
@allenmchan #24
