### ISSUE TITLE
Stop supporting older versions of Kafka - plus improve user and maintainer experience

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-kafka#156]
Supporting multiple versions of Kafka is too much of a burden, so let us just focus on one and be specific about two things:

## 1. Explicitly state the version range of Kafka the output supports.

Maintaining multiple major branches of this plugin has demonstrably been bad for users and bad for us as maintainers. It's confusing to users, and it's frustrating for maintainers when we have to invest time in figuring out what can and cannot be backported.

Proposal:

1) Simplify user experience: Remove the compatibility matrix and replace it with a version range.
2) Simplify maintenance: Only maintain one branch of Kafka plugins.

## 2. Grace period after Kafka upstream releases

Problem: Literally day-1 of every Kafka release we have 2-3 users pinging us "When will Kafka X.Y.Z be supported?" and frankly this is setting everyone up for a constant stream of irritation and annoyance. It would be better for everyone if users did not feel the urgency in pinging us every time Kafka is released and also if we did not feel like we are constantly chasing a never-ending stream of releases.

Proposal:

1) Set user expectations by documenting a grace period that begins with each Kafka change, during which, users should not be pinging us about new version support.
2) For during this grace period, one of the maintainers will test the new release of Kafka and update the documentation if it is supported.
 

----

Implementation: 

The new documentation will read this way:

```
This plugin uses Kafka Client 1.0.0. For broker compatibility, see the official https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Ma
trix[Kafka compatibility reference].

If you're using a plugin version that was released after {version}, see the https://www.elastic.co/guide/en/logstash/master/plugins-inputs-kafka.h
tml[latest plugin documentation] for updated information about Kafka compatibility. If you require features not yet available in this plugin (incl
uding client version upgrades), please file an issue with details about what you need..
```

(With correct kafka client version details)

This should solve the problems mentioned above.

**Comment by jordansissel** [comment]
I'm going to move forward with this and add a note in the README of this repo and somewhere appropriate in the docs for both kafka input/output plugins.

Rough specification:

In order to set user expectations and reduce energy spent in when-will-it-be-released communication loops, we will set a 2-month release cycle for this plugin. Stop investing in this multi-kafka-branch approach (5.x, 6.x, master) and just focus on master.

Impact:

* Only support the latest Kafka client library which transitively selects which Kafka broker versions are supported

**Comment by jordansissel** [comment]
Next steps:

* [ ] Add note in README about release cycle
* [ ] Add note in docs/index.asciidoc about release cycle

**Comment by jordansissel** [comment]
As for compatibility, this relies on the Kafka java client  documentation accuracy, and Kafka says this:

> Starting with version 0.10.2, Java clients (producer and consumer) have acquired the ability to communicate with older brokers. Version 0.11.0 clients can talk to version 0.10.0 or newer brokers

This means we can have kafka output use the latest (0.11.0.0) client and it'll successfully talk with 0.10.0.0 brokers. If it breaks, we can defer to the Kafka project for debugging/troubleshooting.

**Comment by acchen97** [comment]
@jordansissel thanks for putting thought into this, I like the overall goals.

I'm good with just maintaining one branch going forward and defining compatibility with a client version range. We'll still need to support 0.9 for some time; I'm not too worried about 0.8 and we can figure out a deprecation path for it. For some context, HDP 2.4 shipped Mar 2016 and bundled Kafka 0.9, but HDP 2.5 and 2.6 (latest) both bundle 0.10.x, so 0.9 should hopefully be nearing the end of its cycle there as well. I suspect Hadoop vendors still support a majority of Kafka deployments out there today.

For handling upstream releases, are you proposing we move to 2 month time based releases for the Kafka input/output plugins? We could also instead have a 2 month grace period per upstream Kafka minor release where we wouldn't be committing to a specific release cadence, and if we don't have compatibility after 2 months they can still file issues/ERs for it.

**Comment by jordansissel** [comment]
@acchen97 good feedback! THank you :)

I've updated my rough proposal in the comment: https://github.com/logstash-plugins/logstash-output-kafka/issues/156#issuecomment-335319839

**Comment by acchen97** [comment]
@jordansissel I'm good with the changes, thanks.

Let's define the grace period as 6 weeks after each Kafka minor release. Also, it'd be a good idea to document this grace period both in the input/output READMEs **and** plugin documentation.

**Comment by jordansissel** [comment]
^^ minor point -- we only document the *client* version we use of kafka, not the broker. broker-client compatibility is up to Confluent.

This has historically meant that, based on Confluent's documentation on Kafka, client version X works with broker X+1. We don't need to answer questions anymore about broker compatibility, because Confluent answers this already.

**Comment by jordansissel** [comment]
The initial implementation of this doc change is now merged: https://github.com/logstash-plugins/logstash-input-kafka/pull/237 

Next, I need to update the docs for all supported versions of logstash on both input and output kafka plugins.

* [ ] 5.6 input
* [ ] 5.6 output
* [ ] 6.0 input
* [ ] 6.0 output
* [ ] 6.1 input
* [ ] 6.1 output
* [ ] 6.x input
* [ ] 6.x output
* [ ] master input
* [ ] master output

(Some of these may not require any changes if the version of the plugin is the same across Logstash releases)

**Comment by jordansissel** [comment]
Created 8 PRs to change the input and output plugin docs. See https://github.com/logstash-plugins/logstash-output-kafka/issues/156#issuecomment-347950437 for links.

After these are merged, the next steps are:

* publish the plugin branch that comes with Logstash 5.6.x
* edit the docs for all the old versions of Logstash in the logstash-docs repo

**Comment by jordansissel** [comment]
Created 10 more PRs against logstash-docs to sync the changes in the upstream plugin PRs into the docs repository (to avoid excess work regenerating docs)

**Comment by jordansissel** [comment]
This is deployed. I spot-checked a few of the docs pages and they look updated to me.

Closing!
