### ISSUE TITLE
Need to be able to specify message key for output message

### ISSUE THREAD

**Issue by ScottChapman** [logstash-plugins/logstash-output-kafka#16]
The documentation refers to a property which doesn't appear to be available.

Mentioned here: https://github.com/joekiller/logstash-kafka/issues/53

**Comment by jiacai2050** [comment]
6 months have passed, Has anyone worked on this issue ?

**Comment by talevy** [comment]
@ScottChapman @jiacai2050 apologies.

looks like this ticket deals with the pre-0.8 producer client for java.
We have upgraded to use the new producer starting with the `2.x` version of 
this plugin.

One thing that came with this was the ability to set a `message_key` setting.

**Comment by talevy** [comment]
Closing this issue since we have upgraded to a new producer client since, which adds this functionality.
