### ISSUE TITLE
It keeps pulling data again and again from input source

### ISSUE THREAD

**Issue by codeforgeek** [logstash-plugins/logstash-output-kafka#161]
Hi, 
I am using kafka output plugin with elasticsearch and input plugin. 
Goal is to index every document pushed in the ES to kafka.

My config file.

```
input {
        elasticsearch {
                hosts => ["localhost:9200"]
                index => "liferay-20116"
        }
}
output {
      kafka {
        topic_id => "elastic-topic-index"
        codec => json
      }
}
```
Now once I restart logstash and put a consumer to the topic, it reads data from ES. That is working.

But after reading the content from topic, it waits for a while and then re-read everything again! Which is weird to me.

Please help, as this is bit urgent.

**Comment by jsvd** [comment]
the elasticsearch input does not perform a tail on index, every time it executes it will [perform a query](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elasticsearch.html#plugins-inputs-elasticsearch-query) and dump results to the outputs. Until elasticsearch implements the changes API this will be how the plugin works.

**Comment by jsvd** [comment]
closing this since it is not related to the kafka output.
