### ISSUE TITLE
Better handle org.apache.kafka.common.errors.RecordTooLargeException

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-kafka#178]
Currently we retry indefinitely when encountering this error. We should:

1. Always log these errors at 'warn'
2. Consider drop/log, or DLQ as paths for this permanent failure.

**Comment by praseodym** [comment]
See #193; fixed in #194.

**Comment by roaksoax** [comment]
Closing as this has been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/pull/29, in Logstash Kafka Integration plugin version 10.5.0
