### ISSUE TITLE
How can stop  files retry without kill process?

### ISSUE THREAD

**Issue by TiaraH** [logstash-plugins/logstash-output-kafka#182]
Version:6.2.2
Operating System:Linux

When data with incorrect topic name try to send to kafka thru logstash, it will retry again and nerver give up, how can I stop this file retry without modify config or kill process and keep this files down?

**Comment by jakelandis** [comment]
I don't believe that there is a means today. However, see https://github.com/logstash-plugins/logstash-output-kafka/issues/167. Once the dead letter queue is enabled for this output, then it should be able stop the retries. 

I am going to close this issue please re-open if I am misunderstanding your question.  Also please add any commentary for the dead letter queue requirements for this plugin over at https://github.com/logstash-plugins/logstash-output-kafka/issues/167.
