### ISSUE TITLE
Unable to recover from RecordTooLargeException

### ISSUE THREAD

**Issue by davehagler** [logstash-plugins/logstash-output-kafka#190]
When RecordTooLargeException is returned by the kafka server, it is an unhandled exception and logstash retries forever, driving up the CPU on the host.

This is the Debug message in the log
KafkaProducer.send() failed: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.

Can RecordTooLargeException be caught explicitly and handled the same as Timeout or Interrupt exceptions?

https://github.com/logstash-plugins/logstash-output-kafka/blob/146f3f5dce786b8a8b385ec86b27b1b1fb1ab9ad/lib/logstash/outputs/kafka.rb#L259

```
      futures = batch.collect do |record| 
        begin
          # send() can throw an exception even before the future is created.
          @producer.send(record)
        rescue org.apache.kafka.common.errors.TimeoutException => e
          failures << record
          nil
        rescue org.apache.kafka.common.errors.InterruptException => e
          failures << record
          nil
        rescue org.apache.kafka.common.errors.SerializationException => e
          # TODO(sissel): Retrying will fail because the data itself has a problem serializing.
          # TODO(sissel): Let's add DLQ here.
          failures << record
          nil
        end
      end.compact
```

**Comment by MorrieAtElastic** [comment]
Note that these same problems apparently exist in the kafka input plugin as well. A customer's experience in V5.6:

>At the moment we have increase the message size in the kafka output (logstash collector) and kafka input (logstash indexer) as well as kafka itself.

 >After we fixed the issue between logstash collector (kafka output) and kafka we ended up with a completely blocked logstash indexer because the same restriction there as well. But, unfortunately, the logging is even worse in the kafka input because nothing is logged there that there is an issue with message size.

 >So, if the messages are bigger in kafka than the logstash kafka input plugin has configured, the whole pipeline is blocked again without any warning message.

Will changes to the Kafka Input Plugin be handled through this ER or should I file a separate ER for updates to the Kafka Input Plugin?

**Comment by roaksoax** [comment]
Closing as this has been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/pull/29, in Logstash Kafka Integration plugin version 10.5.0
