### ISSUE TITLE
Separate behaviour for retriable and non-retriable exceptions

### ISSUE THREAD

**Issue by praseodym** [logstash-plugins/logstash-output-kafka#193]
Currently this plugin will retry producing events for any exception, even those that are not retriable (e.g. a `SerializationException`). By default there is [no limit on the number of retries](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html#plugins-outputs-kafka-retries) which causes these kind of failures to infinitely hang the entire Logstash pipeline.

Fortunately, the Kafka client library already provides a [`RetriableException` base class](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html) for exceptions that are retriable (such as a [`TimeoutException`](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html)). It makes a lot of sense to implement retry logic only for exceptions that inherit `RetriableException` and drop or send-to-DLQ events that are not.

**Comment by praseodym** [comment]
Implemented in #194.

**Comment by roaksoax** [comment]
Closing as this has been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/pull/29, in Logstash Kafka Integration plugin version 10.5.0
