### ISSUE TITLE
Kafka 2.0 support

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-kafka#203]
Kafka 2.0 has been released. This is to track the support of (and/or testing efforts around) the new major version for the output plugin.

**Comment by jsvd** [comment]
fixed in https://github.com/logstash-plugins/logstash-output-kafka/pull/206 and shipped in version 7.2.0 https://github.com/logstash-plugins/logstash-output-kafka/blob/master/CHANGELOG.md#720
