### ISSUE TITLE
Feat - Add support for zstd and compression level - Kafka 2.1

### ISSUE THREAD

**Issue by davewat** [logstash-plugins/logstash-output-kafka#208]
Add support for Kafka 2.1 and specifically zstd compression.  Should also have option to set compression level.

**Comment by roaksoax** [comment]
Closing this issue as this has been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/commit/e5bf1265f937c1d2a954e0c6ed24f63375d39bf7
