### ISSUE TITLE
Release Kafka 2.0 producer

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-kafka#24]
#15 added the new producer available in 0.8.2. This is currently in master, but needs to be released to RubyGems.org.

Initially release a beta1 with LS 2.0 beta1 (with https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/237) and then release a GA version. This breaks backward compatibility, so should accompany an upgrade guide and a blog.

**Comment by elvarb** [comment]
Any ETA on this?

Does that mean that the current plugin only supports sending to Kafka 0.8 and not 0.8.2 ? 
Or is that when this producer is added to the plugin you will not be able to send to Kafka 0.8 and only 0.8.2?

**Comment by joekiller** [comment]
0.8 and 0.8.2 are protocol compatible so you have no worries
