### ISSUE TITLE
Logstash 2.0.0 upgrade path

### ISSUE THREAD

**Issue by sherzberg** [logstash-plugins/logstash-output-kafka#30]
I have upgraded to logstash 2 and now it appears that there are some missing configuration keys (these are the ones I was using prior to 2.0 that I could not find an alternative config value to):

- partition_key_format
- queue_buffering_max_ms
- producer_type

Can these no longer be used? I see they were removed in the commits, but don't see a reason why or an alternative to these configuration values.

**Comment by talevy** [comment]
> * partition_key_format

This partition key string is comparable to the key of the message in the new Kafka producer. `message_key`.

> * queue_buffering_max_ms

I am not aware of a comparable configuration for the new producer. I suggest configuring the `batch size` and `buffer_memory` instead

> * producer_type

`async` vs `sync` producer types are configured by the number of acknowledgements you expect. You can configure this using the `acks` configuration option. Setting `acks=0` is essentially equivalent to the `async` producer_type without any waits on acknowledgement of any kind.

let me know if those help!

**Comment by sherzberg** [comment]
@talevy I got your suggestions to work. Thank you for the quick response!
