### ISSUE TITLE
Support LZ4 compression type in producer

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-kafka#40]
https://github.com/joekiller/jruby-kafka/blob/v1.5.0/lib/jruby-kafka/producer.rb#L17

**Comment by joekiller** [comment]
should be good in v1.6

**Comment by roaksoax** [comment]
Closing this issue as this has been fixed in https://github.com/logstash-plugins/logstash-integration-kafka/commit/e5bf1265f937c1d2a954e0c6ed24f63375d39bf7

**Comment by joekiller** [comment]
Never say never.
