### ISSUE TITLE
Add cname support for bootstrap_servers

### ISSUE THREAD

**Issue by ksenji** [logstash-plugins/logstash-output-kafka#42]
Bootstrap_servers take a list of ip addresses or a vip. It is better to use a CNAME and have the brokers behind the CNAME (so that the changes to broker are agnostic to the logstash plugin) and when the logstash starts, we can lookup all the ip addresses behind the CNAME and start the kafka Producer

**Comment by joekiller** [comment]
Did your producer not resolve cname addresses? I'm pretty sure I used
cnames in the past.

**Comment by ksenji** [comment]
If we configure cname Kafka producer, currently it would resolve to just one ip address (which ever the DNS lookup gets) and tries to work with it just as if only one node was given in the bootstrap servers and if that broker happens to be down (In cloud the brokers can go down and they can be getting replaced. It could be that the entry in a cname is stale temporarily or there was a network partition or the broker could have just went down etc) then the producer cannot make any progress (even though Kafka cluster is in a healthy state) because it cannot fetch the metadata. 

This can be viewed as a enhancement in the Kafka producer itself too. This is similar to what zookeeper does (with StaticHostProvider). But until Kafka fixes the producer, we can expand the cname to all the ip addresses behind it and send it over to the producer. I have the pull request (https://github.com/logstash-plugins/logstash-output-kafka/pull/43) which does the same.

**Comment by joekiller** [comment]
Gotcha. +1

**Comment by joekiller** [comment]
PS you need to sign the CLA for the PR to be accepted. Look at the checks at the bottom of #43

**Comment by ksenji** [comment]
I signed the CLA and got the confirmation email as well, however the PR does not reflect that for some reason.

**Comment by ksenji** [comment]
It now cleared the CLA, can you please allow Jenkins to run.

**Comment by suyograo** [comment]
@ksenji @joekiller I don't think we should be resolving cnames inside of Logstash. I understand the issue, but this sounds wrong to me. Logstash should be agnostic to lower level networking concepts like `cnames`. Maybe create an issue in Kafka producer @ksenji ?
