### ISSUE TITLE
0.9 Kafka beta producer: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyOutputStream 

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-kafka#50]
Testing the 0.9 Kafka beta output plugin and running into the following exception which I can reproduce locally:

```
input{
generator{
count=>10
}
}
output{
kafka { 
topic_id => "test" 
compression_type => "snappy" 
workers => 1 
}
}
```

This is an error at runtime.  If snappy compression_type is enabled, it throws a classnotfoundexception.

```
kafka producer threw exception, restarting {:exception=>org.apache.kafka.common.KafkaException: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyOutputStream, :level=>:warn, :file=>"logstash/outputs/kafka.rb", :line=>"131", :method=>"register"}
```

Even though the jar and the offending class is available at:
./vendor/bundle/jruby/1.9/gems/jruby-kafka-1.5.0-java/lib/org/xerial/snappy/snappy-java/1.1.1.7/snappy-java-1.1.1.7.jar

Classloading issue?

**Comment by joekiller** [comment]
What OS are you trying on?

**Comment by ppf2** [comment]
Mac OS using the tar.gz LS package.

**Comment by joekiller** [comment]
I figured as much. Mac does not natively support snappy. You should try a
`brew install snappy`. Or check HTTP://macappstore.org/snappy/

**Comment by ppf2** [comment]
Thanks.  The snappy install didn't help.  I expect this to occur on other platforms too since it's just using the .tar.gz installation package and the error indicates that it cannot find the org.xerial.snappy.SnappyOutputStream java class.  Seems like a classloading issue to me (eg. not reading from where the .jar file is packaged with the LS install, or something else ...)

**Comment by allenmchan** [comment]
This is not just on CentOS. My test is on CentOS 7 which had snappy working in the 0.8.x producer.
