### ISSUE TITLE
Better documentation of plugin options

### ISSUE THREAD

**Issue by joshuar** [logstash-plugins/logstash-output-kafka#55]
Some of the descriptions of the plugin options are next to useless.  For example:

```
message_keyedit

Value type is string
There is no default value for this setting.
The key for the message
```

_The key for the message_ is not a useful description.  Some of the other option descriptions are equally vague, like `topic_id` and the `*_serializer` options.  Can they be elaborated on, or can we link back to the official Kafka docs for what these options correspond to?

**Comment by joshuar** [comment]
Also, if we are exposing Kafka options, but renaming them, we should reference what the Kafka paramter is called or potentially provide a lookup table for comparison?

**Comment by talevy** [comment]
@joshuar, valid.

This `message_key` is associated with the `ProducerRecord` object used by the Java KafkaProducer. This is why there is not equivalent configuration option to the producer in it's internal Java counterpart.

This key is used by Kafka for partitioning and log compaction.

reference: http://kafka.apache.org/082/javadoc/org/apache/kafka/clients/producer/ProducerRecord.html
as described by docs: 

> If no partition is specified but a key is present a partition will be chosen using a hash of the key. If neither key nor partition is present a partition will be assigned in a round-robin fashion.
> ...
> The key that will be included in the record

would adding something like this ^^^ be what you had in mind?

**Comment by joshuar** [comment]
@talevy I think that would be awesome!

**Comment by talevy** [comment]
Cool. feel free to LGTM this: https://github.com/logstash-plugins/logstash-output-kafka/pull/56

**Comment by GlenRSmith** [comment]
This can be closed, right? @joshuar @talevy

**Comment by talevy** [comment]
@GlenRSmith guess so, you're right. thanks for the ping!
