### ISSUE TITLE
logstash-2.3.1 and kafka-0.9  error

### ISSUE THREAD

**Issue by zhao141** [logstash-plugins/logstash-output-kafka#61]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: current
- Operating System: win7

i follow guide code. but logstash start error,and standard stdout is ok.

error msg: 
`cmd->
logstash.bat -f logstash.conf
io/console not supported; tty will not be manipulated
[31mfetched an invalid config {:config=>"input {\n  file {\n    path => \"D:\\l
ogs\\app\\action.log\"\n  }\n}\n\noutput { \n\tstdout { \n\t\t\tcodec => dots \n
\t\t} \n\tkafka { \n\t\tbroker_list => \"localhost:9092\" \n\t\ttopic_id => \"te
st\" \n\t\tcompression_codec => \"snappy\" \n\t\t} \n}\n\n#output {\n#    stdout
 {}\n#}\n", :reason=>"Could not find jar files under D:/Program Files/logstash-2
.3.1/vendor/local_gems/9ef8ef4f/logstash-output-kafka-3.0.0.beta2/vendor/jar-dep
endencies/runtime-jars/*.jar", :level=>:error}[0m
The signal HUP is in use by the JVM and will not work correctly on this platform`

**Comment by zhao141** [comment]
i can`t find jar in logstash and logstash-kafka plugin path.
related to version?

**Comment by talevy** [comment]
@zhao141. I believe this problem was fixed in the latest commit and was released recently: `3.0.0.beta3`

do you mind updating your plugin from `beta2` to `beta3` by running the following in your logstash directory

```
$ bin/logstash-plugin install --version 3.0.0.beta3 logstash-output-kafka
```

hope that helps!

**Comment by zhao141** [comment]
i`m try. but same mistake.
`D:\logstash-output-kafka-master>gem build logstash-output-kafka.gemspec
WARNING:  open-ended dependency on logstash-codec-plain (>= 0) is not recommende
d
  if logstash-codec-plain is semantically versioned, use:
    add_runtime_dependency 'logstash-codec-plain', '~> 0'
WARNING:  open-ended dependency on logstash-codec-json (>= 0) is not recommended

  if logstash-codec-json is semantically versioned, use:
    add_runtime_dependency 'logstash-codec-json', '~> 0'
WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not
recommended
  if logstash-devutils is semantically versioned, use:
    add_development_dependency 'logstash-devutils', '~> 0'
WARNING:  open-ended dependency on poseidon (>= 0, development) is not recommend
ed
  if poseidon is semantically versioned, use:
    add_development_dependency 'poseidon', '~> 0'
WARNING:  open-ended dependency on snappy (>= 0, development) is not recommended

  if snappy is semantically versioned, use:
    add_development_dependency 'snappy', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: logstash-output-kafka
  Version: 3.0.0.beta4
  File: logstash-output-kafka-3.0.0.beta4.gem`


`D:\>"Program Files\logstash-2.3.1\bin\logstash-plugin.bat" install logstash-outp
ut-kafka-master\logstash-output-kafka-3.0.0.beta4.gem
io/console not supported; tty will not be manipulated
Validating logstash-output-kafka-master\logstash-output-kafka-3.0.0.beta4.gem
Installing logstash-output-kafka
Installation successful`



`D:\Program Files\logstash-2.3.1\bin>logstash.bat -f logstash.conf
io/console not supported; tty will not be manipulated
[31mfetched an invalid config {:config=>"input {\n  file {\n    path => \"D:\\l
ogs\\app\\action.log\"\n  }\n}\n\noutput { \n\tstdout { \n\t\t\tcodec => dots \n
\t\t} \n\tkafka {\n\t\tbroker_list => \"localhost:9092\" \n\t\ttopic_id => \"tes
t\" \n\t\tcodec => plain {\n      \t\tformat => \"%{message}\"\n    \t\t}\n\t\t}
\n}\n\n#output {\n#    stdout {}\n#}\n", :reason=>"Could not find jar files unde
r D:/Program Files/logstash-2.3.1/vendor/local_gems/c9ad1ca2/logstash-output-kaf
ka-3.0.0.beta4/vendor/jar-dependencies/runtime-jars/*.jar", :level=>:error}[0m
The signal HUP is in use by the JVM and will not work correctly on this platform`

**Comment by zhao141** [comment]
i can`t find jar-dependencies path and any jar. why?

**Comment by talevy** [comment]
Hi @zhao141, this was a known error in one of the beta releases for this plugin.

@suyograo, didn't we clean this up for `beta4`?

**Comment by suyograo** [comment]
no, beta4 works

**Comment by suyograo** [comment]
will check on windows

**Comment by zhao141** [comment]
sorry,may be my problem! i change command to `D:\>"Program Files\logstash-2.3.1\bin\logstash-plugin.bat" install logstash-output-kafka-master\logstash-output-kafka` is ok!

i don`t konw can`t appoint to full name,
but, program eventually find him

**Comment by talevy** [comment]
awesome @zhao141 thanks for letting us know!
