### ISSUE TITLE
log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.producer.ProducerConfig)

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-kafka#62]
- Version: LS 2.3.2+ logstash-output-kafka (3.0.0.beta3)
- Steps to Reproduce:  

Just run a pipeline with a Kafka output plugin.  You will see a warning message .

log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.producer.ProducerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Looks like a log4j config issue, probably benign (though will it affect our ability to pass through informational/debugging messages from the Kafka producer client?

**Comment by joekiller** [comment]
The plugin should invoke the log4j setup similar to how the 2.0 did: https://github.com/logstash-plugins/logstash-output-kafka/blob/2.x/lib/logstash/outputs/kafka.rb#L105

Yes people will miss valuable messages otherwise.

**Comment by suyograo** [comment]
@joekiller thanks, can you review https://github.com/logstash-plugins/logstash-output-kafka/pull/63

**Comment by suyograo** [comment]
BTW, I fixed up the input as well.

**Comment by Ranjith0t0k** [comment]
val spark : SparkSession = SparkSession.builder()
  .appName("Smack_Kafka_Spark")
  .master("local[*]")
  .getOrCreate()
