### ISSUE TITLE
Can output_kafka consume event from input_zeromq

### ISSUE THREAD

**Issue by mizeng** [logstash-plugins/logstash-output-kafka#69]
I have one server has input_zeromq and output_elasticsearch, and it works well. 
However I just added output_kafka, but it seems not work since I can't find any event from Kafka client.

So I'm wondering if output_kafka can consume event from input_zeromq

Version: logstash 2.3.2
Operating System: Ubuntu 14.04
Config File (if you have sensitive info, please remove it): I have 1 input config file and 2 output config files as below:
input_zeromq:
input {
zeromq {
topology => 'pushpull'
type => 'pull-input'
}
}

output_kafka:
output {
kafka {
topic_id => 'logstash_logs'
bootstrap_servers => 'aaaa:9092'
}
}

output_elasticsearch:
output {
elasticsearch {
hosts => ['bbbb:9200']
}
}

**Comment by talevy** [comment]
There should not be any specific reason that the kafka output would deal with input_zeromq messages any differently. are you sure you can send to Kafka with this configuration outside of logstash? or with a different input?

**Comment by mizeng** [comment]
thanks. I'll check my Kafka settings.
