### ISSUE TITLE
Support Kafka 0.10

### ISSUE THREAD

**Issue by thoughtpoet** [logstash-plugins/logstash-output-kafka#70]
Adding an enhancement request for supporting Kafka v0.10.

**Comment by talevy** [comment]
thanks @thoughtpoet, this will be added soon!

**Comment by oyld** [comment]
That's a good idea.

**Comment by ppf2** [comment]
Also linking the Kafka input equivalent of this request: https://github.com/logstash-plugins/logstash-input-kafka/pull/94 for those who may be looking.

**Comment by talevy** [comment]
PR can be found here: #72
