### ISSUE TITLE
kafka init deadlock issue

### ISSUE THREAD

**Issue by joekiller** [logstash-plugins/logstash-output-kafka#8]
It seems like occasionally the Kafka output causes Logstash's initialization process to stop and then Logstash doesn't function.

https://github.com/joekiller/logstash-kafka/issues/46

**Comment by joekiller** [comment]
I believe this is related to: https://issues.apache.org/jira/browse/KAFKA-524

I think I have it fixed and will do a PR once I finish testing.

**Comment by joekiller** [comment]
Hey guys I need some guidance on this one. I asked a question in the mailing list but I'll ask it here as well. https://groups.google.com/forum/#!topic/logstash-users/9Vnf_ZoJB-8

There was a bug in kafka plugin where if a log4j logger isn't setup then the zookeeper library can deadlock the startup of the plugin, thus deadlocking logstash.  I fixed it but I used the function `Logstash::Logger.setup_log4j` which from what I can tell might be deprecated or at least isn't being called by much. 

When I run the plugin with logstash, all is well and the deadlock no longer exists and there is now kafka logging, which is good but when I try to run rspec logs the logger doesn't seem to be core logstash `@logger` doesn't seem to be initialized properly so the target (https://github.com/elasticsearch/logstash/blob/33ace9296ab906d74c0f3f121398bc6bd890ec5a/lib/logstash/logging.rb#L64) returns a null object and then the test blows up trying to get `target.path` here: https://github.com/elasticsearch/logstash/blob/33ace9296ab906d74c0f3f121398bc6bd890ec5a/lib/logstash/logging.rb#L64

Does anyone have some guidance as to how y'all would prefer me to handle this? I could try in the kafka part to retrieve the root logger and just add a kafka appender but I'm unsure if there is even a root appender during the rspec running.

**Comment by talevy** [comment]
Hey @joekiller, I will investigate this now. thanks for following up!

**Comment by talevy** [comment]
@joekiller is this what you had in mind? https://github.com/logstash-plugins/logstash-output-kafka/pull/10

**Comment by joekiller** [comment]
That looks pretty good. You can remove the log4j dependency as slf4j-log4j
implements the interface as needed.

We need a similar patch in the kafka input as well. Same dependency stuff
as I've mentioned and the setup log4j call in the register function.

I think this makes the plugins stable for a release.  I've been working in
some new features for jruby-kafka which I'll do PR's but this is good for
now.

@joekiller <https://github.com/joekiller> is this what you had in mind? #10
<https://github.com/logstash-plugins/logstash-output-kafka/pull/10>

—
Reply to this email directly or view it on GitHub
<https://github.com/logstash-plugins/logstash-output-kafka/issues/8#issuecomment-71565920>
.

**Comment by talevy** [comment]
https://github.com/logstash-plugins/logstash-output-kafka/pull/10 merged
