### ISSUE TITLE
please add label/tag for plugin-version 4.x.y

### ISSUE THREAD

**Issue by ppuschmann** [logstash-plugins/logstash-output-kafka#94]
Currently there are only the following tags/branches available:
- v2.0.5
- v3.0.0
- v3.0.0.beta2
- v3.0.0.beta4
- v3.0.1
- v5.0.0
- v5.0.1
- v5.0.2
- v5.0.3
- v5.0.4

I'd like to use version 4.x.y of this plugin, but don't find any hints about the dependencies.

Can you create a matchting tag/branch for 4.x.y?

**Comment by wiibaa** [comment]
@suyograo for some reason the rubygem publish of 4.0.0 did not create the github tag. 

IMHO what must be done is:
* create a branch for kafka0.9 support in 2.4/5.0, 
* prepare a 4.0.1 for actual 2.4 support simply by changing the gemspec dependencies for plugin api to relax the constraint from `~>2.0` to the usual `<=2.99, >= 1.60`
* publish 4.0.1

Am I right ? 
If yes can you please create a branch "4.x" from this commit => https://github.com/logstash-plugins/logstash-output-kafka/commit/2fd6cb948fdd173f2458759e8d253e731d8de926
and I would do a PR on it asap

**Comment by pickypg** [comment]
There is also a 4.0.1 version that has been pushed for the output plugin, which is also not tagged.

**Comment by wongchao** [comment]
how to install 4.x by bin/logstash-plugin ? --version?

**Comment by ppuschmann** [comment]
After this long time I'll close the issue.
Development of Logstash continued and we managed to upgrade to newer version somewhere in the past.
